kitchen/app/kitchen/urls.py
from django.contrib import admin
from django.urls import path
from django.http import HttpResponse
from dashboard.views import home

def healthz(request):
    return HttpResponse()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('healthz', healthz),
    path('', home),
]

kitchen/app/menu_orders/models.py
from django.db import models


class MenuOrder(models.Model):

    created_at = models.DateTimeField(auto_now_add=True,
        verbose_name="Créé le")

    identifier = models.UUIDField(blank=False,
        verbose_name="Unique identifier for traceability")

    menu = models.CharField(blank=True, max_length=40,
        verbose_name="Selected menu",
        choices=[
            ('STANDARD', 'Standard menu'),
            ('XXL', 'XXL Menu')
        ]
    )

    preparation_estimated_start = models.DateTimeField(null=True,
        verbose_name="Preparation: estimated start"
    )

    preparation_estimated_end = models.DateTimeField(null=True,
        verbose_name="Preparation: estimated start"
    )

    preparation_start = models.DateTimeField(null=True,
        verbose_name="Preparation: start date/time"
    )
    preparation_end = models.DateTimeField(null=True,
        verbose_name="Preparation: end date/time"
    )

    status = models.CharField(default='NEW', max_length=20,
        verbose_name="Status",
        choices=[
            ('SCHEDULED', 'Scheduled to be cooked'),
            ('IN_PROGRESS', 'Being cooked'),
            ('COOKED', 'Cooked - ready to be picked'),
            ('PICKED', 'Picked by delivery service')
        ]
    )

kitchen/app/dashboard/views.py
from menu_orders.models import MenuOrder
from django.shortcuts import render


def home(request):
    """
    Dashboard for monitoring activity
    """
    orders = MenuOrder.objects.all().order_by('-created_at')

    return render(request, "home.html",
    {
        "orders": orders
    })

kitchen/app/dashboard/templates/home.html
<h1>Kitchen - Tableau de bord</h1>

<h3>Commandes</h3>

<table>
  <tr>
    <th>Date</th>
    <th>Identifiant</th>
    <th>Menu</th>
    <th>Statut</th>
    <th>Date préparation</th>
    <th>Date fin préparation</th>
  </tr>
  {% for order in orders %}
    <tr>
      <td>{{ order.created_at | date:'r' }}</td>
      <td>{{ order.identifier }}</td>
      <td>{{ order.get_menu_display }}</td>
      <td>{{ order.get_status_display }}</td>
      <td>
        {% if order.preparation_start %}
          {{ order.preparation_start | date:'r' }}
        {% else %}
          Estimée à : {{ order.preparation_estimated_start | date:'r' }}
        {% endif %}
      </td>
      <td>
        {% if order.preparation_end %}
          {{ order.preparation_end | date:'r' }}
        {% else %}
          Estimée à : {{ order.preparation_estimated_end | date:'r' }}
        {% endif %}
      </td>
    </tr>
  {% endfor %}
</table>

<style>
  body {
    padding: 30px
  }
  table td,th {
    border: solid 1px;
    padding: 5px 15px;
  }
  table {
    max-width: 1100px;
    border-collapse: collapse;
  }
</style>